seo:
  site_name: Sof Kapa Photography
  title: Sof Kapa Photography | Melbourne Photographer
  description: Melbourne photographer specializing in lifestyle, travel and street photography
  keywords: photography, photographer, melbourne, brand, lifestyle, food, travel, street, small business
  social_image: /assets/social_images/socialshare.jpg
  author: Sof Kapa
  favicon_image:
_comments: 
  title: Max 70 characters
  social_image: Landscape 1200 x 600 px
social:
  instagram_username: sofkapa_photo
  facebook_url:
  twitter_username:
