seo:
  site_name: Sof Kapa Photography
  title: Sof Kapa Photography | Melbourne Lifestyle Photographer
  description: Melbourne based lifestyle photographer working with people and brands
  keywords: photography, photographer, melbourne, brand, lifestyle, food, travel, street, small business
  social_image: /assets/social_images/social_share_v2.png
  author: Sof Kapa
  favicon_image: 
_comments: 
  title: Max 70 characters
  social_image: Landscape 1200 x 600 px
social:
  instagram_username: sofkapa_photo
  facebook_url:
  twitter_username:
