seo:
  site_name: Sof Kapa Photography
  title: Photography Portfolio
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username: